
name: Build app

on: 
  release:
    types: [published]
      
jobs:
  
  build_on_mac_x64:
    runs-on: macOS-latest
    steps:
    # checkout branch
    - uses: actions/checkout@v3

    # install node
    - uses: actions/setup-node@master
      with:
        node-version: 18.16

    - name: Update dependencies
      run: npm update
    
    - name: Install dependencies
      run: npm install

    - name: Build app for intel
      run: npm run make -- --platform darwin

    - name: See directory
      run: ls ./out

    - name: See directory
      run: ls -hl ./out/materialserver-darwin-x64
    
    - name: Change directory
      run: cd ./out/materialserver-darwin-x64

    - name: Compress release
      run: zip materialserver-macos-x64.zip materialserver.app

    - name: See directory
      run: ls -hl

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: 'materialserver-macos-x64.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}

  build_on_mac_arm64:
    runs-on: macOS-latest
    steps:
    # checkout branch
    - uses: actions/checkout@v3

    # install node
    - uses: actions/setup-node@master
      with:
        node-version: 18.16

    - name: Update dependencies
      run: npm update
    
    - name: Install dependencies
      run: npm install

    - name: Build app for arm
      run: npm run make -- --arch=arm64 --platform=darwin 

    - name: See directory
      run: ls ./out

    - name: See directory
      run: ls ./out/materialserver-darwin-arm64

    - name: Compress release
      run: zip ./materialserver-macos-arm64.zip out/materialserver-darwin-arm64/materialserver.app

    - name: See directory
      run: ls

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './materialserver-macos-arm64.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}